query GetPostBySlug($id: ID!, $idType: PostIdType!) {
  post(id: $id, idType: $idType) {
    title
    title_spanish
    excerpt
    slug
    date
    featuredImage {
      node {
        sourceUrl
        srcSet
        mediaDetails {
          sizes {
            height
            name
            width
            sourceUrl
          }
        }
      }
    }
    author {
      node {
        name
        firstName
        lastName
        avatar {
          url
        }
      }
    }
    categories {
      edges {
        node {
          name
        }
      }
    }
    tags {
      edges {
        node {
          name
        }
      }
    }
    content
    content_spanish
  }
  posts(first: 3, where: { orderby: { field: DATE, order: DESC } }) {
    edges {
      node {
        title
        title_spanish
        excerpt
        slug
        date
        featuredImage {
          node {
            sourceUrl
            srcSet
            mediaDetails {
              sizes {
                height
                name
                width
                sourceUrl
              }
            }
          }
        }
        author {
          node {
            name
            firstName
            lastName
            avatar {
              url
            }
          }
        }
        categories {
          edges {
            node {
              name
            }
          }
        }
        tags {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}
